server:
  port: 8001

spring:
  application:
    name: client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis-plus:   #\u5176\u4ED6\u914D\u7F6E\u89C1\u7B14\u8BB0\u6216\u5B98\u7F51
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath*:mapper/*.xml
  # \u914D\u7F6E\u5B9E\u4F53\u7C7B\u5305\u5730\u5740
  type-aliases-package: com.zh.client.entity
  # \u9A7C\u5CF0\u8F6C\u4E0B\u5212\u7EBF
  configuration:
    map-underscore-to-camel-case: true
